### ISSUE TITLE
Main handbook update list

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/handbook#191]
This is the list of current handbook updates found on the [master branch](https://github.com/hyphacoop/handbook/tree/master)

Legend: (U)PDATE / (K)EEP / (R)EMOVE

 

_We should update this top post with current status of each, so once U/R items are fixed, check it._

### Hypha Worker Co-operative

* [x] [About Us](https://github.com/hyphacoop/handbook/blob/master/co-operative.md): K
    * [x] [Press and Public Speaking](https://github.com/hyphacoop/handbook/blob/master/press.md): U (ask Andi)
* [x] [Look and Feel](https://github.com/hyphacoop/handbook/blob/master/look-and-feel.md): K
* [x] [Mission, Vision and Values](https://github.com/hyphacoop/handbook/blob/master/vision.md): K
* [x] [Co-operative Principles](https://github.com/hyphacoop/handbook/blob/master/co-operative-principles.md): K
* [x] [Bylaws](https://github.com/hyphacoop/handbook/blob/master/bylaws.md): U (ben PR)
* [x] [Board of Directors](https://github.com/hyphacoop/handbook/blob/master/board-of-directors.md): K
* [x] [Member-workers](https://github.com/hyphacoop/handbook/blob/master/member-workers.md): U (Vincent to fix member count, 4 founding members + 3 )
    * >Hypha has seven member-workers, or members, four of which are full members and three are probationary members. Members are expected to acknowledge the duties of their relationship with Hypha by signing the Membership Acknowledgement.
* [x] [Compensation and Benefits](https://github.com/hyphacoop/handbook/blob/master/compensation-benefits.md): K
    * [x] [Employee Salary Guide](https://github.com/hyphacoop/handbook/blob/master/salary.md): U (await decision from WG)

### Our Virtual Office

* [x] [Onboarding](https://github.com/hyphacoop/handbook/blob/master/onboarding.md): U (Vincent separate out the pages)
    * [x] Bulletin Board: U (Lexa to review alongside workplace safety tickets in Ops)
    * [x] Our Virtual Office: U (Vincent ask for decison about Loomio and Service Inventory)
    * [x] Onboarding Checklist: U (make this Onboarding and Offboarding, Elon is working on Offboarding)
* [x] [Coordination 🚧](https://github.com/hyphacoop/handbook/blob/master/coordination.md): U (get Lexa's opinion on using this as a "when to use which tool" relating to https://github.com/hyphacoop/organizing-private/issues/237)
    * [x] Primary Coordination: U (remove from "The following table" to end of table, "Primary Coordination" -> "GitHub")
    * [x] Making Decisions: R
    * [x] Real-time Chat: U
    * [x] Shared Calendar: U
    * [x] Signal: U (new section)
    * [x] Drive: U (new section)
* [x] #201
* [ ] [Roles 🚧](https://github.com/hyphacoop/handbook/blob/master/roles.md): U (Lexa) - https://github.com/hyphacoop/organizing-private/issues/247
* [x] [Meetings](https://github.com/hyphacoop/handbook/blob/master/meetings.md): K
* [x] [Working Open](https://github.com/hyphacoop/handbook/blob/master/working-open.md): K
* [ ] [Finance](https://github.com/hyphacoop/handbook/blob/master/finance.md): U (Ben to update with Finance)
    - [ ] [Financial Accounts](https://github.com/hyphacoop/handbook/blob/master/finance.md#financial-accounts): U (TransferWise -> Wise, delete CAD 10,000, maybe change to CAD 100,000)
    - [ ] [Invoicing Clients](https://github.com/hyphacoop/handbook/blob/master/finance.md#invoicing-clients): U
        * [x]  - delete the following
          - >In cases where an invoice is not collected in time for payroll, or failed to be collected altogether, this is treated as a cost to the Co-operative and we strongly advocate that this not affect the timely payroll to the Member.
        >
        >In order to create invoices and to collect payments, there are three general steps that need to be performed in order.
       * [x] Generating Timesheets: R
       * [x] Generating Invoices: R
       * [x] Settling Payments: R
    - [ ] [Member Payroll](https://github.com/hyphacoop/handbook/blob/master/finance.md#member-payroll)
        * [ ] [Calculating Member Wages](https://github.com/hyphacoop/handbook/blob/master/finance.md#calculating-member-wages)
        * [ ] [Expense Reimbursement](https://github.com/hyphacoop/handbook/blob/master/finance.md#expense-reimbursement)
        * [ ] [Public Holiday Pay](https://github.com/hyphacoop/handbook/blob/master/finance.md#public-holiday-pay)
    - [ ] [Reporting & Remitting Taxes](https://github.com/hyphacoop/handbook/blob/master/finance.md#reporting--remitting-taxes)
        * [ ] [Corporate Income Tax (RC)](https://github.com/hyphacoop/handbook/blob/master/finance.md#corporate-income-tax-rc)
        * [ ] [Payroll Deduction (RP)](https://github.com/hyphacoop/handbook/blob/master/finance.md#payroll-deduction-rp)
        * [ ] [GST/HST (RT)](https://github.com/hyphacoop/handbook/blob/master/finance.md#gsthst-rt)
        * [ ] [Holding crypto-currency](https://github.com/hyphacoop/handbook/blob/master/finance.md#holding-crypto-currency)
* [x] [Fiscal Sponsorship](https://github.com/hyphacoop/handbook/blob/master/fiscal-sponsorship.md): K
* [x] [Holidays, Time off, and Leaves](https://github.com/hyphacoop/handbook/blob/master/holidays.md): U (Lexa)
* [x] [Pet Policy](https://github.com/hyphacoop/handbook/blob/master/pet.md): K
* [x] Novel Coronavirus (2019) : R

--

* [x] [Guides 🚧](https://github.com/hyphacoop/handbook/blob/master/guides.md): U (make every guide into a subpage)
    - [x] [Calendar](https://github.com/hyphacoop/handbook/blob/master/guides/calendar.md): U 
    - [x] [Email](https://github.com/hyphacoop/handbook/blob/master/guides/email.md): U (see 180)
    - [x] [Expense Reimbursement](https://github.com/hyphacoop/handbook/blob/master/guides/expense-reimbursement.md): K
    - [x] [Hiring](https://github.com/hyphacoop/handbook/blob/master/guides/hiring.md): R (remove onboarding)
    - [ ] [Infrastructure - Virtual Machines](https://github.com/hyphacoop/handbook/blob/master/guides/virtual-machines.md)
    - [ ] [Infrastructure - Advanced Topics](https://github.com/hyphacoop/handbook/blob/master/guides-infrastructure-advanced.md)
    - [ ] [Infrastructure - Initial Setup](https://github.com/hyphacoop/handbook/blob/master/guides-infrastructure-initial-setup.md)
    - [x] [Invoices](https://github.com/hyphacoop/handbook/blob/master/guides/invoices.md): U (ask @dasanchez and @YurkoWasHere to rewrite/ most of it is outdated)
    - [x] [Issue Labels](https://github.com/hyphacoop/handbook/blob/master/guides/issue-labels.md): K
    - [ ] [Inactivating Membership](https://github.com/hyphacoop/handbook/blob/master/guides/inactivating-membership.md): R (add inactivating membership to offboarding)
    - [x] [Initiatives](https://github.com/hyphacoop/handbook/blob/master/guides/initiatives.md): U (see with Andi if we reorganize in a new location (add to each proper section instead of being in guides))
    - [ ]  [Meetings](https://github.com/hyphacoop/handbook/blob/master/guides/meetings.md): U (location and content (probably to long..))
    - [x] [Payroll](https://github.com/hyphacoop/handbook/blob/master/guides/payroll.md): U (ask @dasanchez  to rewrite)
    - [x] [Reporting HST](https://github.com/hyphacoop/handbook/blob/master/guides/reporting-hst.md): K
    - [x] [Sensitive Data](https://github.com/hyphacoop/handbook/blob/master/guides/sensitive-data.md): K
    - [x] [Signatures](https://github.com/hyphacoop/handbook/blob/master/guides/signatures.md): K
        Signing external documents: U (change HelloSign -> DropboxSign)
    - [x] [Shortlinks](https://github.com/hyphacoop/handbook/blob/master/guides/shortlinks.md): K
    - [x] Timesheets: R
    - [ ] [Virtual Machines](https://github.com/hyphacoop/handbook/blob/master/guides/virtual-machines.md): U (ask @YurkoWasHere, about infra stuff being moved to another section)
    - [ ] [Voicemail](https://github.com/hyphacoop/handbook/blob/master/guides/voicemail.md): U (ask @YurkoWasHere )
    - [ ] [VPN](https://github.com/hyphacoop/handbook/blob/master/guides/vpn.md): U (ask @YurkoWasHere )
    - [x] References: R from Content Index
* [x] [Templates](https://github.com/hyphacoop/handbook/blob/master/templates.md): K
* [x] [How We Use Data](https://github.com/hyphacoop/handbook/blob/master/data.md): U
* [ ] [Reading Pool](https://github.com/hyphacoop/handbook/blob/master/reading-pool.md): U (how do we integrate Roo/ link to Roo's sheet)
* [x] [Glossary](https://github.com/hyphacoop/handbook/blob/master/glossary.md): U (Delete Clip)

**Comment by tripledoublev** [comment]
On the coordination page, I have removed the _Making Decisions_ section because its process was outdated. 
I still believe the handbook would benefit from integrating such content. Commenting on this matter as a reminder to rewrite and reintegrate the decision making process.

**Comment by benhylau** [comment]
## TODO

- @writerly03 
  - [Press and Public Speaking](https://github.com/hyphacoop/handbook/blob/update-remove-items-191/press.md): U (ask Andi)
  - Think thru Initiatives page
- @benhylau 
  - [Bylaws](https://github.com/hyphacoop/handbook/blob/update-remove-items-191/bylaws.md): U (ben PR)
- @LexaMichaelides 
  - https://github.com/hyphacoop/organizing/issues/266
  - https://github.com/hyphacoop/organizing/issues/217
  - Lexa send reviewed version of technical offboard
- @tripledoublev 
  - Our Virtual Office: U (Vincent ask for decison about Loomio and Service Inventory): drop Service Inv, keep Loomio

## Notes
- section for onboarding
  - Lexa: above tickets re: workplace
- another section for offboarding
  - Lexa: digital accounts that need to be turned off for each offboard
- Coordination will wait for: https://github.com/hyphacoop/organizing-private/issues/237
- Initiatives page, link https://miro.com/app/board/uXjVPfDB5Eo=/ 🔒
- Roles: @LexaMichaelides @benhylau to discuss at next Ops meeting

**Comment by benhylau** [comment]
Sent PR for:
- https://github.com/hyphacoop/handbook/pull/198
- https://github.com/hyphacoop/handbook/pull/199

**Comment by benhylau** [comment]
@LexaMichaelides pls make sure these are incorporated into our onboarding documentation:
- https://github.com/hyphacoop/organizing/issues/511
- https://handbook.hypha.coop/templates.html#tasks

**Comment by writerly03** [comment]
@benhylau pretty sure it's a mishmash from the handbook, old onboarding lists you put together (maybe to onboard me?)

**Comment by writerly03** [comment]
@tripledoublev I've updated the press page content. What workflow makes the most sense? The copy is here but I can update the file directly here? https://docs.google.com/document/d/1TNOgF49csF4iVGtPN2kz_8I0rLRH_TpM089I382xAsk/edit#heading=h.ke1769r49zw8

**Comment by writerly03** [comment]
@tripledoublev Sorry, should have been more specific in my ask - I know the process to update the file itself. Just wondering if you wanted to do something different for all these little edits since we are all making so many. But I can follow the usual process. I don't find it very intuitive and it takes me a long time so I will likely wait until later in the week to start this part.

**Comment by writerly03** [comment]
Closed this issue, but it does tie in the work done on the handbook in April https://github.com/hyphacoop/organizing/issues/495

**Comment by tripledoublev** [comment]
Checked off on/offboarding.

During this edit, I noticed a broken link for a guide on SSH Keys. It is not mentionned on the list here but was wondering if this is something we should add eventually.

**Comment by tripledoublev** [comment]
Closing this issue since our handbook has been through a complete rework since the creation of these tasks
